general:
  kafka-topic: trader-updates

spring:
  datasource:
    url: jdbc:h2:mem:midasdb;DB_CLOSE_DELAY=-1 #in-memory database 
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop #auto creates tables from @Entity class
    show-sql: true #print query to console 
  h2:
    console:
      enabled: true #at localhost:8080/h2-console
  kafka:
    consumer:
      group-id: midas-group-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jpmc.midascore.foundation
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
